/*
jQuery(".btn-slide").click(function(){
	jQuery(".panel").slideToggle("slow");
});
jQuery("#cancel-button").click(function(){
  jQuery(".panel").fadeOut("slow");
});
jQuery("#activate-product-button").click(function(){
  jQuery(".panel").fadeOut("slow");
});
*/
