#!/usr/bin/env python
# -*- coding: utf-8 -*-
# ISO 4217 International Currency Codes
# Taken from http://en.wikipedia.org/wiki/ISO_4217

ISO_4217_CURRENCY_CODES = (
    (u"AED", u"784", 2, u"United Arab Emirates dirham", u"United Arab Emirates",),
    (u"AFN", u"971", 2, u"Afghan afghani", u"Afghanistan",),
    (u"ALL", u"008", 2, u"Albanian lek", u"Albania",),
    (u"AMD", u"051", 2, u"Armenian dram", u"Armenia",),
    (u"ANG", u"532", 2, u"Netherlands Antillean guilder", u"Netherlands Antilles",),
    (u"AOA", u"973", 2, u"Angolan kwanza", u"Angola",),
    (u"ARS", u"032", 2, u"Argentine peso", u"Argentina",),
    (u"AUD", u"036", 2, u"Australian dollar", u"Australia, Australian Antarctic Territory, Christmas Island, Cocos (Keeling) Islands, Heard and McDonald Islands, Kiribati, Nauru, Norfolk Island, Tuvalu",),
    (u"AWG", u"533", 2, u"Aruban guilder", u"Aruba",),
    (u"AZN", u"944", 2, u"Azerbaijani manat", u"Azerbaijan",),
    (u"BAM", u"977", 2, u"Bosnia and Herzegovina konvertibilna marka", u"Bosnia and Herzegovina",),
    (u"BBD", u"052", 2, u"Barbados dollar", u"Barbados",),
    (u"BDT", u"050", 2, u"Bangladeshi taka", u"Bangladesh",),
    (u"BGN", u"975", 2, u"Bulgarian lev", u"Bulgaria",),
    (u"BHD", u"048", 3, u"Bahraini dinar", u"Bahrain",),
    (u"BIF", u"108", 0, u"Burundian franc", u"Burundi",),
    (u"BMD", u"060", 2, u"Bermudian dollar (customarily known as Bermuda dollar)", u"Bermuda",),
    (u"BND", u"096", 2, u"Brunei dollar", u"Brunei, Singapore",),
    (u"BOB", u"068", 2, u"Boliviano", u"Bolivia",),
    (u"BOV", u"984", 2, u"Bolivian Mvdol (funds code)", u"Bolivia",),
    (u"BRL", u"986", 2, u"Brazilian real", u"Brazil",),
    (u"BSD", u"044", 2, u"Bahamian dollar", u"Bahamas",),
    (u"BTN", u"064", 2, u"Bhutanese ngultrum", u"Bhutan",),
    (u"BWP", u"072", 2, u"Botswana pula", u"Botswana",),
    (u"BYR", u"974", 0, u"Belarusian ruble", u"Belarus",),
    (u"BZD", u"084", 2, u"Belize dollar", u"Belize",),
    (u"CAD", u"124", 2, u"Canadian dollar", u"Canada",),
    (u"CDF", u"976", 2, u"Congolese franc", u"Democratic Republic of Congo",),
    (u"CHE", u"947", 2, u"WIR Bank (complementary currency)", u"Switzerland",),
    (u"CHF", u"756", 2, u"Swiss franc", u"Switzerland, Liechtenstein",),
    (u"CHW", u"948", 2, u"WIR Bank (complementary currency)", u"Switzerland",),
    (u"CLF", u"990", 0, u"Unidad de Fomento (funds code)", u"Chile",),
    (u"CLP", u"152", 0, u"Chilean peso", u"Chile",),
    (u"CNY", u"156", 1, u"Chinese yuan", u"China (Mainland)",),
    (u"COP", u"170", 0, u"Colombian peso", u"Colombia",),
    (u"COU", u"970", 2, u"Unidad de Valor Real", u"Colombia",),
    (u"CRC", u"188", 2, u"Costa Rican colon", u"Costa Rica",),
    (u"CUC", u"931", 2, u"Cuban convertible peso", u"Cuba",),
    (u"CUP", u"192", 2, u"Cuban peso", u"Cuba",),
    (u"CVE", u"132", 0, u"Cape Verde escudo", u"Cape Verde",),
    (u"CZK", u"203", 2, u"Czech koruna", u"Czech Republic",),
    (u"DJF", u"262", 0, u"Djiboutian franc", u"Djibouti",),
    (u"DKK", u"208", 2, u"Danish krone", u"Denmark, Faroe Islands, Greenland",),
    (u"DOP", u"214", 2, u"Dominican peso", u"Dominican Republic",),
    (u"DZD", u"012", 2, u"Algerian dinar", u"Algeria",),
    (u"EEK", u"233", 2, u"Estonian kroon", u"Estonia",),
    (u"EGP", u"818", 2, u"Egyptian pound", u"Egypt",),
    (u"ERN", u"232", 2, u"Eritrean nakfa", u"Eritrea",),
    (u"ETB", u"230", 2, u"Ethiopian birr", u"Ethiopia",),
    (u"EUR", u"978", 2, u"Euro", u"16 European Union countries, Andorra, Kosovo, Monaco, Montenegro, San Marino, Vatican City; see eurozone",),
    (u"FJD", u"242", 2, u"Fiji dollar", u"Fiji",),
    (u"FKP", u"238", 2, u"Falkland Islands pound", u"Falkland Islands",),
    (u"GBP", u"826", 2, u"Pound sterling", u"United Kingdom, Crown Dependencies (the Isle of Man and the Channel Islands), certain British Overseas Territories (South Georgia and the South Sandwich Islands, British Antarctic Territory and British Indian Ocean Territory)",),
    (u"GEL", u"981", 2, u"Georgian lari", u"Georgia",),
    (u"GHS", u"936", 2, u"Ghanaian cedi", u"Ghana",),
    (u"GIP", u"292", 2, u"Gibraltar pound", u"Gibraltar",),
    (u"GMD", u"270", 2, u"Gambian dalasi", u"Gambia",),
    (u"GNF", u"324", 0, u"Guinean franc", u"Guinea",),
    (u"GTQ", u"320", 2, u"Guatemalan quetzal", u"Guatemala",),
    (u"GYD", u"328", 2, u"Guyanese dollar", u"Guyana",),
    (u"HKD", u"344", 2, u"Hong Kong dollar", u"Hong Kong Special Administrative Region",),
    (u"HNL", u"340", 2, u"Honduran lempira", u"Honduras",),
    (u"HRK", u"191", 2, u"Croatian kuna", u"Croatia",),
    (u"HTG", u"332", 2, u"Haitian gourde", u"Haiti",),
    (u"HUF", u"348", 2, u"Hungarian forint", u"Hungary",),
    (u"IDR", u"360", 0, u"Indonesian rupiah", u"Indonesia",),
    (u"ILS", u"376", 2, u"Israeli new sheqel", u"Israel",),
    (u"INR", u"356", 2, u"Indian rupee", u"Bhutan, India, Nepal",),
    (u"IQD", u"368", 0, u"Iraqi dinar", u"Iraq",),
    (u"IRR", u"364", 0, u"Iranian rial", u"Iran",),
    (u"ISK", u"352", 0, u"Icelandic króna", u"Iceland",),
    (u"JMD", u"388", 2, u"Jamaican dollar", u"Jamaica",),
    (u"JOD", u"400", 3, u"Jordanian dinar", u"Jordan",),
    (u"JPY", u"392", 0, u"Japanese yen", u"Japan",),
    (u"KES", u"404", 2, u"Kenyan shilling", u"Kenya",),
    (u"KGS", u"417", 2, u"Kyrgyzstani som", u"Kyrgyzstan",),
    (u"KHR", u"116", 0, u"Cambodian riel", u"Cambodia",),
    (u"KMF", u"174", 0, u"Comoro franc", u"Comoros",),
    (u"KPW", u"408", 0, u"North Korean won", u"North Korea",),
    (u"KRW", u"410", 0, u"South Korean won", u"South Korea",),
    (u"KWD", u"414", 3, u"Kuwaiti dinar", u"Kuwait",),
    (u"KYD", u"136", 2, u"Cayman Islands dollar", u"Cayman Islands",),
    (u"KZT", u"398", 2, u"Kazakhstani tenge", u"Kazakhstan",),
    (u"LAK", u"418", 0, u"Lao kip", u"Laos",),
    (u"LBP", u"422", 0, u"Lebanese pound", u"Lebanon",),
    (u"LKR", u"144", 2, u"Sri Lanka rupee", u"Sri Lanka",),
    (u"LRD", u"430", 2, u"Liberian dollar", u"Liberia",),
    (u"LSL", u"426", 2, u"Lesotho loti", u"Lesotho",),
    (u"LTL", u"440", 2, u"Lithuanian litas", u"Lithuania",),
    (u"LVL", u"428", 2, u"Latvian lats", u"Latvia",),
    (u"LYD", u"434", 3, u"Libyan dinar", u"Libya",),
    (u"MAD", u"504", 2, u"Moroccan dirham", u"Morocco, Western Sahara",),
    (u"MDL", u"498", 2, u"Moldovan leu", u"Moldova (except Transnistria)",),
    (u"MGA", u"969", 0.7, u"Malagasy ariary", u"Madagascar",),
    (u"MKD", u"807", 2, u"Macedonian denar", u"Republic of Macedonia",),
    (u"MMK", u"104", 0, u"Myanma kyat", u"Myanmar",),
    (u"MNT", u"496", 2, u"Mongolian tugrik", u"Mongolia",),
    (u"MOP", u"446", 1, u"Macanese pataca", u"Macau Special Administrative Region",),
    (u"MRO", u"478", 0.7, u"Mauritanian ouguiya", u"Mauritania",),
    (u"MUR", u"480", 2, u"Mauritian rupee", u"Mauritius",),
    (u"MVR", u"462", 2, u"Maldivian rufiyaa", u"Maldives",),
    (u"MWK", u"454", 2, u"Malawian kwacha", u"Malawi",),
    (u"MXN", u"484", 2, u"Mexican peso", u"Mexico",),
    (u"MXV", u"979", 2, u"Mexican Unidad de Inversion (UDI) (funds code)", u"Mexico",),
    (u"MYR", u"458", 2, u"Malaysian ringgit", u"Malaysia",),
    (u"MZN", u"943", 2, u"Mozambican metical", u"Mozambique",),
    (u"NAD", u"516", 2, u"Namibian dollar", u"Namibia",),
    (u"NGN", u"566", 2, u"Nigerian naira", u"Nigeria",),
    (u"NIO", u"558", 2, u"Cordoba oro", u"Nicaragua",),
    (u"NOK", u"578", 2, u"Norwegian krone", u"Norway, Bouvet Island, Queen Maud Land, Peter I Island",),
    (u"NPR", u"524", 2, u"Nepalese rupee", u"Nepal",),
    (u"NZD", u"554", 2, u"New Zealand dollar", u"Cook Islands, New Zealand, Niue, Pitcairn, Tokelau",),
    (u"OMR", u"512", 3, u"Omani rial", u"Oman",),
    (u"PAB", u"590", 2, u"Panamanian balboa", u"Panama",),
    (u"PEN", u"604", 2, u"Peruvian nuevo sol", u"Peru",),
    (u"PGK", u"598", 2, u"Papua New Guinean kina", u"Papua New Guinea",),
    (u"PHP", u"608", 2, u"Philippine peso", u"Philippines",),
    (u"PKR", u"586", 2, u"Pakistani rupee", u"Pakistan",),
    (u"PLN", u"985", 2, u"Polish złoty", u"Poland",),
    (u"PYG", u"600", 0, u"Paraguayan guaraní", u"Paraguay",),
    (u"QAR", u"634", 2, u"Qatari rial", u"Qatar",),
    (u"RON", u"946", 2, u"Romanian new leu", u"Romania",),
    (u"RSD", u"941", 2, u"Serbian dinar", u"Serbia",),
    (u"RUB", u"643", 2, u"Russian rouble", u"Russia, Abkhazia, South Ossetia",),
    (u"RWF", u"646", 0, u"Rwandan franc", u"Rwanda",),
    (u"SAR", u"682", 2, u"Saudi riyal", u"Saudi Arabia",),
    (u"SBD", u"090", 2, u"Solomon Islands dollar", u"Solomon Islands",),
    (u"SCR", u"690", 2, u"Seychelles rupee", u"Seychelles",),
    (u"SDG", u"938", 2, u"Sudanese pound", u"Sudan",),
    (u"SEK", u"752", 2, u"Swedish krona/kronor", u"Sweden",),
    (u"SGD", u"702", 2, u"Singapore dollar", u"Singapore, Brunei",),
    (u"SHP", u"654", 2, u"Saint Helena pound", u"Saint Helena",),
    (u"SLL", u"694", 0, u"Sierra Leonean leone", u"Sierra Leone",),
    (u"SOS", u"706", 2, u"Somali shilling", u"Somalia (except Somaliland)",),
    (u"SRD", u"968", 2, u"Surinamese dollar", u"Suriname",),
    (u"STD", u"678", 0, u"São Tomé and Príncipe dobra", u"São Tomé and Príncipe",),
    (u"SYP", u"760", 2, u"Syrian pound", u"Syria",),
    (u"SZL", u"748", 2, u"Lilangeni", u"Swaziland",),
    (u"THB", u"764", 2, u"Thai baht", u"Thailand",),
    (u"TJS", u"972", 2, u"Tajikistani somoni", u"Tajikistan",),
    (u"TMT", u"934", 2, u"Turkmenistani manat", u"Turkmenistan",),
    (u"TND", u"788", 3, u"Tunisian dinar", u"Tunisia",),
    (u"TOP", u"776", 2, u"Tongan paʻanga", u"Tonga",),
    (u"TRY", u"949", 2, u"Turkish lira", u"Turkey, Northern Cyprus",),
    (u"TTD", u"780", 2, u"Trinidad and Tobago dollar", u"Trinidad and Tobago",),
    (u"TWD", u"901", 1, u"New Taiwan dollar", u"Taiwan and other islands that are under the effective control of the Republic of China (ROC)",),
    (u"TZS", u"834", 2, u"Tanzanian shilling", u"Tanzania",),
    (u"UAH", u"980", 2, u"Ukrainian hryvnia", u"Ukraine",),
    (u"UGX", u"800", 0, u"Ugandan shilling", u"Uganda",),
    (u"USD", u"840", 2, u"United States dollar", u"American Samoa, British Indian Ocean Territory, Ecuador, El Salvador, Guam, Haiti, Marshall Islands, Micronesia, Northern Mariana Islands, Palau, Panama, Puerto Rico, Timor-Leste, Turks and Caicos Islands, United States, Virgin Islands, Bermuda (as well as Bermudian Dollar)",),
    (u"USN", u"997", 2, u"United States dollar (next day) (funds code)", u"United States",),
    (u"USS", u"998", 2, u"United States dollar (same day) (funds code) (one source[who?] claims it is no longer used, but it is still on the ISO 4217-MA list)", u"United States",),
    (u"UYU", u"858", 2, u"Uruguayan peso", u"Uruguay",),
    (u"UZS", u"860", 2, u"Uzbekistan som", u"Uzbekistan",),
    (u"VEF", u"937", 2, u"Venezuelan bolívar fuerte", u"Venezuela",),
    (u"VND", u"704", 0, u"Vietnamese đồng", u"Vietnam",),
    (u"VUV", u"548", 0, u"Vanuatu vatu", u"Vanuatu",),
    (u"WST", u"882", 2, u"Samoan tala", u"Samoa",),
    (u"XAF", u"950", 0, u"CFA franc BEAC", u"Cameroon, Central African Republic, Republic of the Congo, Chad, Equatorial Guinea, Gabon",),
    (u"XAG", u"961", None, u"Silver (one troy ounce)", u"",),
    (u"XAU", u"959", None, u"Gold (one troy ounce)", u"",),
    (u"XBA", u"955", None, u"European Composite Unit (EURCO) (bond market unit)", u"",),
    (u"XBB", u"956", None, u"European Monetary Unit (E.M.U.-6) (bond market unit)", u"",),
    (u"XBC", u"957", None, u"European Unit of Account 9 (E.U.A.-9) (bond market unit)", u"",),
    (u"XBD", u"958", None, u"European Unit of Account 17 (E.U.A.-17) (bond market unit)", u"",),
    (u"XCD", u"951", 2, u"East Caribbean dollar", u"Anguilla, Antigua and Barbuda, Dominica, Grenada, Montserrat, Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines",),
    (u"XDR", u"960", None, u"Special Drawing Rights", u"International Monetary Fund",),
    (u"XFU", None, None, u"UIC franc (special settlement currency)", u"International Union of Railways",),
    (u"XOF", u"952", 0, u"CFA Franc BCEAO", u"Benin, Burkina Faso, Côte d'Ivoire, Guinea-Bissau, Mali, Niger, Senegal, Togo",),
    (u"XPD", u"964", None, u"Palladium (one troy ounce)", u"",),
    (u"XPF", u"953", 0, u"CFP franc", u"French Polynesia, New Caledonia, Wallis and Futuna",),
    (u"XPT", u"962", None, u"Platinum (one troy ounce)", u"",),
    (u"XTS", u"963", None, u"Code reserved for testing purposes", u"",),
    (u"XXX", u"999", None, u"No currency", u"",),
    (u"YER", u"886", 0, u"Yemeni rial", u"Yemen",),
    (u"ZAR", u"710", 2, u"South African rand", u"South Africa",),
    (u"ZMK", u"894", 0, u"Zambian kwacha", u"Zambia",),
    (u"ZWL", u"932", 2, u"Zimbabwe dollar", u"Zimbabwe",),
)

ISO_4217_ALPHA_CODES = [t[0] for t in ISO_4217_CURRENCY_CODES]
ISO_4217_NUMERIC_CODES = [t[1] for t in ISO_4217_CURRENCY_CODES if t[1] is not None]

if __name__ == "__main__":
    from pprint import pprint
    pprint(ISO_4217_ALPHA_CODES)
    pprint(ISO_4217_NUMERIC_CODES)
